name: GitHub Profile 3D Contrib

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"   # once per day

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@v0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: naveen777-github

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "Update 3D contribution graph"
          git push
